### PR TITLE
Improve build and push GitHub Action

### PR DESCRIPTION
**Pull request by niklhut**
This new version uses the respective GitHub Actions to login, build and tag the image. 

At least in my fork the action worked seamlessly, so I suppose it should here too.

### CODE REVIEW

**Comment by Rdeisenroth** [comment]
Thanks, this looks good. Do you think we can make it so that PRs also get their docker images build with a designated tag (like `ghcr.io/rdeisenroth/rubot2:pr-18`)? That would make it more convenient to test PRs

**Review by Rdeisenroth — APPROVED** [review]
LGTM

**Comment by niklhut** [comment]
So we would need to run the docker image on every PR. I guess then we could remove the other build workflow since to build and push the docker image with the pr tag the application needs to build. Or do you want to keep the other workflow?

**Comment by niklhut** [comment]
The action now creates an image for every PR with a tag in the format `pr-xx`. For a push to a branch there is an image with the tag of the branch and if the push was to the main branch the latest tag will also be set. 
I also removed the separate build action since it should be redundant now.

**Review by Rdeisenroth — APPROVED** [review]
LGTM

**Pull request merged**
